assetmanager: ../../Programs/Mac/assetmanager

../../Programs/Mac/assetmanager: AssetManager.rogue
	roguec AssetManager.rogue --main --output=Build/AssetManager --compile
	mkdir -p ../../Programs/Mac
	cp Build/assetmanager ../../Programs/Mac

