update_super: ../SuperC/SuperC.c ../SuperC/SuperC.h

../SuperC/SuperC.c: ../../../SuperC/Source/SuperC.c
	mkdir -p ../SuperC
	cp ../../../SuperC/Source/SuperC.c ../SuperC

../SuperC/SuperC.h: ../../../SuperC/Source/SuperC.h
	mkdir -p ../SuperC
	cp ../../../SuperC/Source/SuperC.h ../SuperC

